### PR TITLE
Fix issue with http.proxy and IPv6 #219

### PR DESCRIPTION
**Pull request by siddhant3s**
Please see issue https://github.com/scalameta/metals-languageclient/issues/219 for details

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
Thanks a lot for your thorough issue and tracking down the cause of this! I think we've had a fair amount of people hit on this without ever figuring out what the core issue was. I've tested this out locally a bit with no issues. I would feel better if we had tests specifically for `fetchMetals`, but I don't expect you to create the suite. However I'm gong to leave this open a bit just to get another ✅ from either @gabro or @tgodzik.

On another note, you _may_ want to also raise this to the folks at Coursier. Looking through their [proxy docs](https://get-coursier.io/docs/other-proxy) this _may_ be something they also want to add there. Thanks again for tracking this down.

**Review by gabro — COMMENTED** [review]
Thanks for tracking this down and for the thorough explanation.
The change LGTM 👍

I would only add a comment above the option referencing your issue, since it may not be obvious why we're doing that only by looking at the code

**Comment by siddhant3s** [comment]
Thanks @ckipp01  and @gabro . I've added a comment as per @gabro's  suggestion. @ckipp01 Once this PR is merged, I'll let the coursier folks know about this.

Is there any other action that needs to be taken around this? What should I do next?

**Comment by ckipp01** [comment]
Thanks @siddhant3s! So dare I say in the next week or so 2.12.13 will be released, and when it is, we'll need to cut another Metals release. So if you're able to wait, this will be release and included in the extensions for that next release.

**Comment by siddhant3s** [comment]
Perfect! Thank you so much for the quick review and accepting the changes.

**Comment by gabro** [comment]
@ckipp01 in general vscode releases are super cheap, so I wouldn't also be opposed to a small dedicated release (unless we have stuff on master which depend on a newer metals server)

**Comment by ckipp01** [comment]
> @ckipp01 in general vscode releases are super cheap, so I wouldn't also be opposed to a small dedicated release (unless we have stuff on master which depend on a newer metals server)

I just took a peak, and we only have dependency updates merged since last release. I'll kickstart the process here and release this to star the process.

**Pull request merged**
