### PR TITLE
Run prettier on PRs

### PR DESCRIPTION
**Pull request by gabro**

### CODE REVIEW

**Comment by tgodzik** [comment]
@gabro that's cool! It would be also useful to have on `metals-vscode`

**Comment by gabro** [comment]
@tgodzik yep, I'm experimenting here so that I can copy-paste the CI configuration to metals-vscode ;)

**Comment by gabro** [comment]
@ckipp01 you may want this for coc-metals as well

**Comment by ckipp01** [comment]
@gabro this is just a format check though correct? If so, I already have it in the ci.

**Comment by gabro** [comment]
Ah, cool! I must've missed it 👍

**Pull request merged**
