### PR TITLE
Exchange for locate-java-home honoring JAVA_HOME

### PR DESCRIPTION
**Pull request by hedefalk**
Fixes https://github.com/scalameta/metals-vscode/issues/657

Both original https://github.com/jvilk/locate-java-home and fork https://github.com/jvilk/locate-java-home/pull/10#issuecomment-906193537

seems somewhat stale/dead so I just cross-published the fixed version under my user-scope on npm.

Don't know if there's a cleaner way, but it would really be nice to close https://github.com/scalameta/metals-vscode/issues/657

### CODE REVIEW

**Comment by tgodzik** [comment]
Maybe we should fork it under scalameta to have it in a more official manner? @ckipp01 @gabro what do you think?

**Comment by ckipp01** [comment]
> Maybe we should fork it under scalameta to have it in a more official manner? @ckipp01 @gabro what do you think?

I'm open for whatever works best for everyone. @hedefalk are you forking it only for this? Or do you plan to keep maintaining it, etc?

**Comment by dos65** [comment]
@hedefalk I've checked this thing and it seems that it works well in current Metals release. At least on Linux.

I'm starting VSCode as: `JAVA_HOME=${value} code .` and see that it's correctly picked using [this function](https://github.com/scalameta/metals-languageclient/blob/87425244724013a92ac5f442fc8e199eb89212d1/src/getJavaHome.ts#L44)

Could you describe the case when it doesn't work?

**Comment by hedefalk** [comment]
@ckipp01 Not sorry, not really planning on maintaining it, I just published because I couldn't get author to: https://github.com/scalameta/metals-vscode/issues/657#issuecomment-907128947

**Comment by tgodzik** [comment]
I checked it again and it seems that locate-java-home is properly picking up JAVA_HOME variable, couldn't reproduce it either.

We could switch for sure, especially if the new fork is bettermaintained.

**Comment by tgodzik** [comment]
Updating to the new fork in https://github.com/scalameta/metals-languageclient/pull/395 Thanks for the help!

**Pull request closed without merging**
